### ISSUE TITLE
1.19.2fabicmod加载错误

### ISSUE THREAD

**Issue by kndxhz** [RealHeart/ZMusic-Mod#6]
![image](https://github.com/RealHeart/ZMusic-Mod/assets/113306265/7307b203-8459-41af-945a-7fdd2c8000a2)
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Fabric Loader' (fabricloader) 0.14.13 with version 0.14.14 or later.
Unmet dependency listing:
	 - Mod 'ZMusic Mod' (zmusic) 3.2.0 requires version 0.14.14 or later of mod 'Fabric Loader' (fabricloader), but only the wrong version is present: 0.14.13!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:60)
	at oolloo.jlw.Wrapper.main(Wrapper.java:53)

[错误报告-2023-07-01_19.00.42.zip](https://github.com/RealHeart/ZMusic-Mod/files/11925624/-2023-07-01_19.00.42.zip)

**Comment by kndxhz** [comment]
就算把别的mob都关了就留fabic和zmusic还是这样

**Comment by RealHeart** [comment]
请使用 0.14.14 或更高版本的 Fabric Loader.
